# Generated by Django 3.2.9 on 2022-01-04 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='CreatedTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='getTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Obtainer', models.ManyToManyField(related_name='Obtainer', to='user.User')),
                ('Publisher', models.ManyToManyField(related_name='Publisher', to='user.User')),
                ('Task', models.ManyToManyField(to='task.Task')),
            ],
        ),
    ]
