# Generated by Django 3.2.9 on 2022-01-04 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_gettask_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='gettask',
            name='Time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
