# Generated by Django 3.2.9 on 2022-01-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20220104_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
