# Generated by Django 3.2.9 on 2022-01-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gettask',
            name='State',
        ),
        migrations.AddField(
            model_name='task',
            name='State',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='JsonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_path', models.CharField(max_length=255)),
                ('Task', models.ManyToManyField(to='task.Task')),
            ],
        ),
        migrations.CreateModel(
            name='ExportCoCo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.IntegerField()),
                ('top', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('text', models.CharField(max_length=20)),
                ('Image', models.ManyToManyField(to='task.Image')),
                ('Task_obtained_id', models.ManyToManyField(to='task.getTask')),
            ],
        ),
    ]
