# Generated by Django 3.2.9 on 2022-01-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20220106_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportcoco',
            old_name='Task_obtained_id',
            new_name='Task_obtained',
        ),
    ]
